### ISSUE TITLE
-filepattern $filepattern issue

### ISSUE THREAD

**Issue by Technical87** [gfody/PowershellModules#4]
Hey,

If I run the following:

`search-index $word -filepattern *.doc,*.docx,*.pdf,*.xlsx,*.xls,*.txt,*.mdb -path $path`

The search runs as expected in relation to the -filepattern, however if i run the command below, don't get any search results, presumably due to the filepattern switch not accepting the input?

`$filepatterns = Get-Content "c:\filepatterns.txt"`
`search-index $word -filepattern *.doc,*.docx,*.pdf,*.xlsx,*.xls,*.txt,*.mdb -path $path`

I've confirmed $filepatterns does function correctly by running write-host "$filepatterns" which returns `*.doc,*.docx,*.pdf,*.xlsx,*.xls,*.txt,*.mdb`

**Comment by gfody** [comment]
`-filePattern` is an array, so if you're getting it from a file you'll need to split the file contents into an array, eg: ```gc $path -split '`r`n'```

**Comment by Technical87** [comment]
Thanks for the heads up gfody. I just changed the txt file to have one file type per line which resolved the issue.
